# Generated by Django 5.2 on 2025-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochazka', '0003_attendance_department_employee_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
