# Generated by Django 5.2 on 2025-06-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochazka', '0004_alter_employee_options_employee_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
